### ISSUE TITLE
Lyrics not updating properly (TypeError: list indices must be integers or slices, not str)

### ISSUE THREAD

**Issue by xtho25** [CezarGab/Overlyrics#8]
Hello there, i am experiencing an issue where Overlyrics is sometimes stuck at Starting... due to this error appearing in the console as well as `update_overlay_text()` not updating. Here is a full log of the console while VERBOSE_MODE is True. (Note: I am using a slighly different version of Overlyrics where the authentication is using the depracated method with an app of my own. I also changed the location of the font and images. I hope that none of that is causing this issue.)

trackName in display_lyrics:  
get_track_info():  Wicked Game
get_track_info() - nova musica: Wicked Game
Entered into update_overlay_text()
trackName in display_lyrics:  Wicked Game
get_track_info():  Wicked Game
get_track_info():  Wicked Game
get_track_info():  Wicked Game
get_track_info():  Wicked Game
Exception in thread Thread-2 (update_display):
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\skarp\Desktop\Code\python\Spotify\Overlyrics-main\Overlyrics.py", line 174, in update_display
    display_lyrics(trackName, artistName, currentProgress, isPaused)
  File "c:\Users\skarp\Desktop\Code\python\Spotify\Overlyrics-main\Overlyrics.py", line 230, in display_lyrics
    lyrics = syncedlyrics.search(searchTerm)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\skarp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\syncedlyrics\__init__.py", line 59, in search
    _l = provider.get_lrc(search_term)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\skarp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\syncedlyrics\providers\musixmatch.py", line 120, in get_lrc
    tracks = body["track_list"]
             ~~~~^^^^^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
get_track_info():  Wicked Game
get_track_info():  Wicked Game
get_track_info():  Wicked Game
get_track_info():  Wicked Game
get_track_info():  Wicked Game
get_track_info():  Wicked Game
get_track_info():  Wicked Game
get_track_info():  Wicked Game
get_track_info():  Wicked Game
....
....

If you need any additional info, feel free to ask, thanks!

**Comment by xtho25** [comment]
Hey there, i found the issue in the syncedlyrics github page: https://github.com/moehmeni/syncedlyrics/issues/35

**Comment by xtho25** [comment]
Hello, it seems like the problem was the old authenication system i was using or ig it just fixed it self somehow since i haven't experienced this issue since yesterday where i wasn't authenicated properly.
